[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "cups>=0.0.6",
    "flask>=3.1.1",
    "os-sys>=0.9.1",
    "python-dotenv>=1.1.0",
    "requests==2.32.3",
]
